variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "private_key_password" {}
variable "region" {}
variable "oke_compartment_ocid" {}
variable "network_compartment_ocid" {}
variable "availability_domain" {}
